[GLOBAL]
pants_version = "2.15.1"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.autoflake",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.pylint",
    "pants.backend.python.typecheck.mypy"
]

[anonymous-telemetry]
enabled = true
repo_id = "9123dd83-3b29-4acd-a6da-1f7d80a294ef"
